import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import AvatarImage from '../components/avatarimage.png'
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import { useRouter } from 'next/router'
import { useRef } from 'react';

export default function Home() {
  const NextRouter = useRouter();
  const searchInputRef = useRef();

  const search = (e) => {
    e.preventDefault()

    const term = searchInputRef.current.value;

    if (!term) { 
      return;
    } else {
      NextRouter.push(`/search?term=${term}`);
    }
  }
 
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        <div className='flex space-x-3 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        <div className='flex space-x-3 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          <div>
          <ViewGridIcon className='h-10 mr-2 p-2 rounded-full hover:bg-gray-200 cursor-pointer' />
          </div>

          <Avatar url={AvatarImage} />
        </div>
      </header>

      <form className='flex flex-col items-center mt-48 flex-grow'>
        <Image src='https://assets.stickpng.com/images/580b57fcd9996e24bc43c51f.png' height={100} width={300}/>
        <div className='flex w-full mt-5 focus-within:shadow-lg max-w-md p-2 rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
          <SearchIcon className='h-5 ml-3 text-gray-500 inline' />
          <input ref={searchInputRef} type='text' className='focus:outline-none rounded-xl flex-grow flex mx-3' />
          <MicrophoneIcon className='h-5 mr-3 inline'/>
        </div>

        <div>
          <button onClick={search} className='btn'>Google Search</button>
          <button onClick={search} className='btn'>I&apos;m feeling lucky</button>
        </div>
      </form>
      </div>
    </>
  )
}
